/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as DocumentosDemoRouteImport } from './routes/documentos-demo'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedViagensIndexRouteImport } from './routes/_authenticated/viagens.index'
import { Route as AuthenticatedViagensViagemIdRouteImport } from './routes/_authenticated/viagens.$viagemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosDemoRoute = DocumentosDemoRouteImport.update({
  id: '/documentos-demo',
  path: '/documentos-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViagensIndexRoute =
  AuthenticatedViagensIndexRouteImport.update({
    id: '/viagens/',
    path: '/viagens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedViagensViagemIdRoute =
  AuthenticatedViagensViagemIdRouteImport.update({
    id: '/viagens/$viagemId',
    path: '/viagens/$viagemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/documentos-demo': typeof DocumentosDemoRoute
  '/offline': typeof OfflineRoute
  '/pesquisa': typeof PesquisaRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/viagens/$viagemId': typeof AuthenticatedViagensViagemIdRoute
  '/viagens/': typeof AuthenticatedViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/documentos-demo': typeof DocumentosDemoRoute
  '/offline': typeof OfflineRoute
  '/pesquisa': typeof PesquisaRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/viagens/$viagemId': typeof AuthenticatedViagensViagemIdRoute
  '/viagens': typeof AuthenticatedViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/documentos-demo': typeof DocumentosDemoRoute
  '/offline': typeof OfflineRoute
  '/pesquisa': typeof PesquisaRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/viagens/$viagemId': typeof AuthenticatedViagensViagemIdRoute
  '/_authenticated/viagens/': typeof AuthenticatedViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/avisos'
    | '/documentos-demo'
    | '/offline'
    | '/pesquisa'
    | '/reservas'
    | '/viagens/$viagemId'
    | '/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/avisos'
    | '/documentos-demo'
    | '/offline'
    | '/pesquisa'
    | '/reservas'
    | '/viagens/$viagemId'
    | '/viagens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/auth'
    | '/avisos'
    | '/documentos-demo'
    | '/offline'
    | '/pesquisa'
    | '/_authenticated/reservas'
    | '/_authenticated/viagens/$viagemId'
    | '/_authenticated/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  AuthRoute: typeof AuthRoute
  AvisosRoute: typeof AvisosRoute
  DocumentosDemoRoute: typeof DocumentosDemoRoute
  OfflineRoute: typeof OfflineRoute
  PesquisaRoute: typeof PesquisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos-demo': {
      id: '/documentos-demo'
      path: '/documentos-demo'
      fullPath: '/documentos-demo'
      preLoaderRoute: typeof DocumentosDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viagens/': {
      id: '/_authenticated/viagens/'
      path: '/viagens'
      fullPath: '/viagens/'
      preLoaderRoute: typeof AuthenticatedViagensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viagens/$viagemId': {
      id: '/_authenticated/viagens/$viagemId'
      path: '/viagens/$viagemId'
      fullPath: '/viagens/$viagemId'
      preLoaderRoute: typeof AuthenticatedViagensViagemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedViagensViagemIdRoute: typeof AuthenticatedViagensViagemIdRoute
  AuthenticatedViagensIndexRoute: typeof AuthenticatedViagensIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedViagensViagemIdRoute: AuthenticatedViagensViagemIdRoute,
  AuthenticatedViagensIndexRoute: AuthenticatedViagensIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AjudaRoute: AjudaRoute,
  AuthRoute: AuthRoute,
  AvisosRoute: AvisosRoute,
  DocumentosDemoRoute: DocumentosDemoRoute,
  OfflineRoute: OfflineRoute,
  PesquisaRoute: PesquisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
